var files_dup =
[
    [ "auxil.c", "auxil_8c.html", "auxil_8c" ],
    [ "auxil.h", "auxil_8h.html", "auxil_8h" ],
    [ "config.h", "config_8h.html", "config_8h" ],
    [ "dance.c", "dance_8c.html", "dance_8c" ],
    [ "dance.h", "dance_8h.html", "dance_8h" ],
    [ "dimacs.c", "dimacs_8c.html", "dimacs_8c" ],
    [ "dimacs.h", "dimacs_8h.html", "dimacs_8h" ],
    [ "error.c", "error_8c.html", "error_8c" ],
    [ "error.h", "error_8h.html", "error_8h" ],
    [ "fileHandling.c", "file_handling_8c.html", "file_handling_8c" ],
    [ "fileHandling.h", "file_handling_8h.html", "file_handling_8h" ],
    [ "free.c", "free_8c.html", "free_8c" ],
    [ "free.h", "free_8h.html", "free_8h" ],
    [ "generate.c", "generate_8c.html", "generate_8c" ],
    [ "generate.h", "generate_8h.html", "generate_8h" ],
    [ "heuristic.c", "heuristic_8c.html", "heuristic_8c" ],
    [ "heuristic.h", "heuristic_8h.html", "heuristic_8h" ],
    [ "hide.c", "hide_8c.html", "hide_8c" ],
    [ "hide.h", "hide_8h.html", "hide_8h" ],
    [ "hrowCover.c", "hrow_cover_8c.html", "hrow_cover_8c" ],
    [ "hrowCover.h", "hrow_cover_8h.html", "hrow_cover_8h" ],
    [ "initDance.c", "init_dance_8c.html", "init_dance_8c" ],
    [ "initDance.h", "init_dance_8h.html", "init_dance_8h" ],
    [ "main.c", "main_8c.html", "main_8c" ],
    [ "main.h", "main_8h.html", "main_8h" ],
    [ "matrixFile.c", "matrix_file_8c.html", "matrix_file_8c" ],
    [ "matrixFile.h", "matrix_file_8h.html", "matrix_file_8h" ],
    [ "parseArgs.c", "parse_args_8c.html", "parse_args_8c" ],
    [ "parseArgs.h", "parse_args_8h.html", "parse_args_8h" ],
    [ "sew.c", "sew_8c.html", "sew_8c" ],
    [ "sew.h", "sew_8h.html", "sew_8h" ],
    [ "solTree.c", "sol_tree_8c.html", "sol_tree_8c" ],
    [ "solTree.h", "sol_tree_8h.html", "sol_tree_8h" ],
    [ "struct.h", "struct_8h.html", "struct_8h" ]
];