# This is a basic workflow to help you get started with Actions

name: publish_doxygen

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Publish Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
      
      - name: Move
        run: |
          shopt -s extglob
          mv './html/*' '.'



