# This is a basic workflow to help you get started with Actions

name: publish_doxygen

# Controls when the workflow will run
on:
  # workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - master
      - gh-pages


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create clean gh-pages branch
        run:  git checkout -b gh-pages
      
      - name: Publish Doxygen
        uses: mattnotmitt/doxygen-action@v1.9.2
      
      
      
      
