# This is a basic workflow to help you get started with Actions

name: publish_doxygen

# Controls when the workflow will run
on:
  # workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - master
      - gh-pages


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish_doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update; sudo apt-get install -y doxygen graphviz texlive-full

      - name: Run Doxygen
        run: |
          git clone https://github.com/sw478/multidimensional-sudoku.git
          mkdir multidimensional-sudoku/build
          cd multidimensional-sudoku/build
          cmake -DOPTION_BUILD_DOCS=ON ..
          make api-docs
        
      - name: Move
        run: mv ./core/build/docs/api-docs ./api
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
      
      
      
      
